column_name_mapping = {

    # common columns defined by site catalyst for all apps
    'geo_city': 'city',
    'geo_country': 'country',
    'post_visid_low': 'visitor_id_low',
    'post_visid_high': 'visitor_id_high',
    'post_cust_hit_time_gmt': 'hit_time_gmt',
    'post_event_list': 'event_list',
    'post_t_time_info': 'timezone',
    'post_mobileappid': 'app_version',
    'post_mobiledayssincefirstuse': 'days_since_first_use',
    'post_mobiledayssincelastuse': 'days_since_last_use',
    'post_mobiledevice': 'mobile_device',
    'post_mobileinstalldate': 'first_launch_date',
    'post_mobilelaunchnumber': 'launch_number',
    'post_mobileosversion': 'mobile_os_version',
    'visit_num': 'visit_num',
    'visit_page_num': 'visit_page_num',

    # columns specific for ugrow
    'post_evar2': 'HSDP_id',
    # 'post_evar3': 'event_pages',
    # 'post_evar4': 'registration_type',
    # 'post_evar5': 'download_documents',
    'post_evar7': 'page_name',
    # 'post_evar9': 'component_version',
    'post_evar13': 'login_type',
    # 'post_evar14': 'remarketing_consent',
    'post_evar17': 'article_category',
    #'post_evar18': 'article_name',
    'post_evar25': 'time_taken_create_account',
    # 'post_evar28': 'language',
    # 'post_evar35': 'product_category',
    # 'post_evar36': 'product_sub_category',
    # 'post_evar37': 'previous_page',
    # 'post_evar38': 'sleep_time',
    # 'post_evar39': 'bed_type',
    # 'post_evar49': 'product_id_app_id',
    # 'post_evar50': 'measuring_type',  # timer, manual, none
    # 'post_evar53': 'notification_message_response',
    # 'post_evar54': 'platform_notification',
    # 'post_evar55': 'crying_time',
    # 'post_evar56': 'service_satisfaction_level',
    'post_evar57': 'service_channel',
    # 'post_evar58': 'social_message',
    # 'post_evar59': 'social_channel',
    'post_evar61': 'notification_message',
    # 'post_evar62': 'widget_used',
    # 'post_evar63': 'app_status',
    # 'post_evar64': 'control_connection_type',
    # 'post_evar65': 'app_id',  # unique
    # 'post_evar66': 'product_model',  # SCH740 means baby thermometer
    # 'post_evar67': 'product_id',  # unique
    # 'post_evar68': 'product_firmware_version',
    # 'post_evar69': 'error_message',
    # 'post_evar74': 'room_temperature',
    # 'post_evar76': 'humidity',
    'post_evar77': 'milestone_added',
    'post_evar80': 'birth_date',
    # 'post_evar81': 'due_date',
    # 'post_evar83': 'baby_age',
    'post_evar84': 'baby_gender',
    'post_evar85': 'card_tracker_item_origin',
    'post_evar86': 'card_tracker_item_timestamp',
    'post_evar88': 'card_id',
    'post_evar89': 'card_category',
    'post_evar90': 'card_type',
    # 'post_evar92': 'bottle_type',
    # 'post_evar93': 'bottle_contents',
    # 'post_evar94': 'bottle_amount',
    # 'post_evar95': 'insight_id',
    # 'post_evar96': 'article_id',
    # 'post_evar97': 'soothing_scene_added',
    # 'post_evar98': 'nugget_pressed',
    'post_evar99': 'floating_button',
    'post_evar100': 'article_view_location'

}
